### ISSUE TITLE
Ошибка при сохранении настроек Оргструктуры

### ISSUE THREAD

**Issue by yakot93** [ITDSystems/alvex-orgchart#32]
Ошибка при сохранении настроек Оргструктуры, кнопка "Настройки интерфейса" -> кнопка "Сохранить"

![image](https://cloud.githubusercontent.com/assets/16797982/19264689/2afe1f34-8fbb-11e6-905b-ac7c4dbf30d9.png)

Alfresco Community 5.1.0 (r127059-b7)
Alvex 3.0 SNAPSHOT 20161010.110655-51

UPD. Посмотрел, что шлет страница при нажатии на кнопку "сохранить" и вручную отправил все тоже самое. Получилось) С страницы администратора по прежнему ошибка.

![image](https://cloud.githubusercontent.com/assets/16797982/19266259/1b15c0e8-8fc2-11e6-8b30-136dfeba1ca4.png)
![image](https://cloud.githubusercontent.com/assets/16797982/19266286/465e88de-8fc2-11e6-9ce6-b25cf9fc7582.png)

**Comment by aviriel** [comment]
На последней сборке не воспроизводится.
