### ISSUE TITLE
Task Assignment not working

### ISSUE THREAD

**Issue by Funies** [ITDSystems/alvex-orgchart#39]
Hi,

I have installed Alvex orgChart on Afresco. I have created the organisational chart, in there there's a role called Director.
I have a workflow that is supposed to use this Orgchart to assign tasks to users.
On the workflow, process id is: my_process and the assignee is: {0}::Director. 
On the repo context file I have the following bean:
 <bean id="MyWorkflowAlvexOrgchart" parent="alvex-orgchart-delegations-manager">
          <property name="matches">
            <list>
              <value>task-assign-after-change:.*@my_process</value>
              <value>task-done:.*@my_process</value>
              <value>process-start@my_process</value>
            </list>
          </property>
         </bean>

The error I get on the log file is: 2017-02-15 09:25:02,852  ERROR [repo.activiti.OrgchartDelegationsManager] [http-apr-8180-exec-1] Issue with assignment resolve happened: null. Assigning to admin

**Comment by aviriel** [comment]
Hi
{0} means that Director will be in the same department as task creator. Your error looks like there is no Director in this department. If a user with such role is in another static department, you can use something like: Department::Director

**Comment by Funies** [comment]
Hi,

Thank you for responding, my test user us called user1, this is a normal
user who is starting the workflow. user1 is in the same unit as a user
called director1 who has the Director role in that unit; hence I used the {0}
.



I've attached a screenshot of my orgstructure, repo bean and processsnippet.

Kind Regards
Lufuno Keohitlhetse

On Wed, Feb 15, 2017 at 12:21 PM, Oksana Kurysheva <notifications@github.com

**Comment by Funies** [comment]
Hi,

I just want to check if you are still looking at my issue.

Kind Regards

On Wed, Feb 15, 2017 at 12:21 PM, Oksana Kurysheva <notifications@github.com

**Comment by Funies** [comment]
Does unit weight have anything to do with task assignments?

Kind Regards

**Comment by aviriel** [comment]
can you attach your workflow, so we can check what's wrong?

**Comment by aviriel** [comment]
No response for 6 months, closing the issue
